[package]
name = "gen"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
num-traits = "0.2"
rand = "0.5"
num-bigint = { version = "0.2", features = ["rand"] }
glass_pumpkin = "0.3.3"
